"""first init

Revision ID: f7a5c0e1df11
Revises: 
Create Date: 2026-05-26 03:04:43.126523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7a5c0e1df11'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade(engine_name: str) -> None:
    """Upgrade schema."""
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name: str) -> None:
    """Downgrade schema."""
    globals()["downgrade_%s" % engine_name]()





def upgrade_engine1() -> None:
    """Upgrade engine1 schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Chats',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.String(), nullable=False),
    sa.Column('messages', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'chat_id')
    )
    op.create_index(op.f('ix_Chats_chat_id'), 'Chats', ['chat_id'], unique=False)
    op.create_index(op.f('ix_Chats_user_id'), 'Chats', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade_engine1() -> None:
    """Downgrade engine1 schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Chats_user_id'), table_name='Chats')
    op.drop_index(op.f('ix_Chats_chat_id'), table_name='Chats')
    op.drop_table('Chats')
    # ### end Alembic commands ###


def upgrade_engine2() -> None:
    """Upgrade engine2 schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Users_id'), 'Users', ['id'], unique=False)
    op.create_index(op.f('ix_Users_username'), 'Users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade_engine2() -> None:
    """Downgrade engine2 schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Users_username'), table_name='Users')
    op.drop_index(op.f('ix_Users_id'), table_name='Users')
    op.drop_table('Users')
    # ### end Alembic commands ###

